# Generated by Django 5.0 on 2023-12-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_drinkscategory_rename_drink_name_drinks_drink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reservation_day', models.CharField(max_length=200)),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
