# Generated by Django 5.0 on 2023-12-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
