# Generated by Django 5.0 on 2023-12-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
    ]
